[package]
name = "lobbylocker-tauri"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
lobbylocker-core.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
rfd.workspace = true
tauri-plugin-opener = "2.7.0"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }

[dev-dependencies]
tempfile.workspace = true

[features]
custom-protocol = ["tauri/custom-protocol"]
